[package]
name = "diskmap"
version = "0.1.0"
edition = "2024"

[dependencies]
flexbuffers = "25.2.10"
nix = { version = "0.30.1", features = ["fs", "process"] }
serde = { version = "1.0.226", features = ["derive"] }
